[package]
name = "kas-tutorials"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2024"
resolver = "2"
publish = false

[dependencies]
env_logger = "0.11"
kas = { version = "0.17.0", features = ["view"] }
kas-wgpu = "0.17.1"
